# Generated by Django 2.2.11 on 2020-03-26 18:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('operation', '0003_banner'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='banner',
            options={'verbose_name': '轮播图', 'verbose_name_plural': '轮播图'},
        ),
    ]
