# Generated by Django 2.2.11 on 2020-03-23 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_auto_20200323_2207'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursetag',
            name='tag',
            field=models.CharField(max_length=100, verbose_name='标签名'),
        ),
    ]
